POST localhost:8080/api/user/refresh
Cookie: Refresh=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1ZGUxMzEzMi0yMGFiLTQ1MWMtOTBiMS03NGZiMjBmMmI3ZTUiLCJ1c2VySWQiOiIwZGU0ZWFiNi1iYTg0LTQxNGUtOTg5OS0wM2YyOGI5ZWFlN2UiLCJleHAiOjE2ODAwNDcxOTd9.ZinepKvp3WNevmtqML_RgN1Y0Gr3PdGeAHmiAtnuZeE